language: java
jdk:
- openjdk7
- oraclejdk7
before_install:
- echo "JAVA6_HOME=$(jdk_switcher home jdk6)" >> gradle.properties
- cat gradle.properties
- export JAVA7_HOME=$(jdk_switcher home jdk7)
after_success:
- gradle travisRelease
env:
  secure: MjANwdcG1f4OPnZnnI4JUdPfeRirj0NMScphOxXkxB9FDrfxH6s8/R9UlxvUhLFV1bVODKaJ8lI8zA/ZQUULFCs+k88XpEbjUAYVdADGW/mOGViQCgFhHhMp2ZtH2OayJbbvR0bXZPvEHSfKK0BYPXcFPSVBAUrsJLdAnhtynMU=
